import { t } from "elysia";

const nullableString = t.Union([t.String(), t.Null()]);
const nullableDateTime = t.Union([t.String({ format: "date-time" }), t.Null()]);

export const telegramSchemas = {
  role: t.Union([t.Literal("caretaker"), t.Literal("emergency"), t.Literal("contact")]),
  authState: t.Union([
    t.Literal("waiting_phone_number"),
    t.Literal("waiting_code"),
    t.Literal("waiting_password"),
    t.Literal("authenticated"),
    t.Literal("expired"),
  ]),
  error: t.Object({
    error: t.String(),
    message: t.String(),
  }),
  authStartBody: t.Object({
    phoneNumber: t.String({ minLength: 8 }),
  }),
  authVerifyCodeBody: t.Object({
    code: t.String({ minLength: 1 }),
  }),
  authStatus: t.Object({
    authState: t.Union([
      t.Literal("waiting_phone_number"),
      t.Literal("waiting_code"),
      t.Literal("waiting_password"),
      t.Literal("authenticated"),
      t.Literal("expired"),
    ]),
    telegramUserId: nullableString,
    connectedAt: nullableDateTime,
    sessionPath: t.String(),
  }),
  contact: t.Object({
    id: t.String(),
    patientId: t.String(),
    role: t.Union([t.Literal("caretaker"), t.Literal("emergency"), t.Literal("contact")]),
    priorityRank: t.Integer(),
    name: t.String(),
    relation: t.String(),
    phoneNumber: t.String(),
    phoneNumberNormalized: t.String(),
    telegramUserId: nullableString,
    telegramChatId: nullableString,
    isActive: t.Boolean(),
    notes: nullableString,
    lastResolvedAt: nullableDateTime,
    createdAt: t.String({ format: "date-time" }),
    updatedAt: t.String({ format: "date-time" }),
  }),
  contactCreateBody: t.Object({
    name: t.String({ minLength: 1 }),
    relation: t.String({ minLength: 1 }),
    phoneNumber: t.String({ minLength: 8 }),
    role: t.Union([t.Literal("caretaker"), t.Literal("emergency"), t.Literal("contact")]),
    priorityRank: t.Optional(t.Integer()),
    notes: t.Optional(t.String()),
    isActive: t.Optional(t.Boolean()),
  }),
  contactUpdateBody: t.Object({
    name: t.Optional(t.String({ minLength: 1 })),
    relation: t.Optional(t.String({ minLength: 1 })),
    phoneNumber: t.Optional(t.String({ minLength: 8 })),
    role: t.Optional(t.Union([t.Literal("caretaker"), t.Literal("emergency"), t.Literal("contact")])),
    priorityRank: t.Optional(t.Integer()),
    notes: t.Optional(t.Union([t.String(), t.Null()])),
    isActive: t.Optional(t.Boolean()),
  }),
  chat: t.Object({
    chatId: t.String(),
    contactId: t.String(),
    title: t.String(),
    lastMessagePreview: nullableString,
    lastMessageAt: nullableDateTime,
    lastMessageId: nullableString,
    unreadCount: t.Integer(),
  }),
  message: t.Object({
    id: t.String(),
    chatId: t.String(),
    direction: t.Union([t.Literal("incoming"), t.Literal("outgoing")]),
    text: t.String(),
    contentType: t.String(),
    sentAt: t.String({ format: "date-time" }),
    senderLabel: nullableString,
  }),
  openChatResponse: t.Object({
    contact: t.Object({
      id: t.String(),
      patientId: t.String(),
      role: t.Union([t.Literal("caretaker"), t.Literal("emergency"), t.Literal("contact")]),
      priorityRank: t.Integer(),
      name: t.String(),
      relation: t.String(),
      phoneNumber: t.String(),
      phoneNumberNormalized: t.String(),
      telegramUserId: nullableString,
      telegramChatId: nullableString,
      isActive: t.Boolean(),
      notes: nullableString,
      lastResolvedAt: nullableDateTime,
      createdAt: t.String({ format: "date-time" }),
      updatedAt: t.String({ format: "date-time" }),
    }),
    chat: t.Object({
      chatId: t.String(),
      contactId: t.String(),
      title: t.String(),
      lastMessagePreview: nullableString,
      lastMessageAt: nullableDateTime,
      lastMessageId: nullableString,
      unreadCount: t.Integer(),
    }),
    messages: t.Array(
      t.Object({
        id: t.String(),
        chatId: t.String(),
        direction: t.Union([t.Literal("incoming"), t.Literal("outgoing")]),
        text: t.String(),
        contentType: t.String(),
        sentAt: t.String({ format: "date-time" }),
        senderLabel: nullableString,
      }),
    ),
  }),
  sendMessageBody: t.Object({
    text: t.String({ minLength: 1 }),
    source: t.Optional(t.String()),
  }),
  replyOption: t.Object({
    id: t.String(),
    label: t.String(),
    text: t.String(),
    source: t.Literal("static"),
  }),
} as const;
